# Use the official Golang image as the base
FROM golang:1.24.5-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the Go modules files and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the application code
COPY . .

# Build the Go server application
RUN go build -o server_app cmd/box.go

# Command to run the server application
CMD ["./server_app"]
