# Use the official Golang image as the base
FROM golang:1.24.5-alpine

# Set the working directory inside the container
WORKDIR /app

# Set environment variable for the client mode
ENV MODE=client

# Copy the Go modules files and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the application code
COPY . .

# Build the Go client application
RUN go build -o client_app cmd/box.go

# Command to run the client application in client mode
CMD ["./client_app"]
